server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: Saireddy@2610
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
  cloud:
    config:
      enabled: false
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true


management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker :
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelBreaker:
        maxAttempts: 3
        waitDuration: 5s
  ratelimiter:
    instances:
      ratingHotelBreaker:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 0s


